name: Test Deno Module

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [~1.37]

    env:
      DENO_DIR: deno_modules

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('deno.jsonc') }}
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Build
        run: deno task build
      - name: Lint
        run: deno task check
      - name: Test
        run: deno task ci
